serenity.project.name=Petstore Framework
serenity.outputDirectory=target/site/serenity
serenity.requirements.types=feature,story
serenity.take.screenshots=FOR_FAILURES
serenity.compress.filenames=true
